---
driver_plugin: vagrant
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: 'http://repo-par.criteo.prod:8080/omnibus_install.sh'

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: [
          'recipe[test-mrepo::mirror]',
        ]
  attributes:
