---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users:
          - vagrant

platforms:
- name: centos-6
  transport:
    name: speedy_ssh
  provisioner:
    chef_omnibus_url:     'http://repo-par.criteo.prod/omnibus_install.sh'
  driver_config:
    box:     opscode-centos-6.7
    box_url: http://filer.criteo.prod/boxes/opscode_centos-6.7.box

suites:
<%= require 'erubis'; Erubis::Eruby.new(File.read('.kitchen_suites.yml')).evaluate %>
